name = "PetoiBittle"
uuid = "5bc1ff43-7751-4008-a957-b2449cec208f"
authors = ["Dmitry Bagaev <bvdmitri@gmail.com>"]
version = "1.0.0"

[compat]
julia = "1.10"
Aqua = "0.8"
JET = "0.9, 0.10"
Test = "1.10"
TestItemRunner = "1.1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "JET", "Test", "TestItemRunner"]
