[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PetoiBittle = "5bc1ff43-7751-4008-a957-b2449cec208f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"

[sources]
PetoiBittle = {path = ".."}
