[deps]
PetoiBittle = "5bc1ff43-7751-4008-a957-b2449cec208f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
